name: Update News for LLMs

on:
  schedule:
    # Run every Sunday at 2 AM UTC
    - cron: '0 2 * * 0'
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-news:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 lxml python-dateutil
    
    - name: Run Wikipedia scraper
      run: |
        python run_wikipedia.py
    
    - name: Commit and push if changed
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add output/newsforllms.html
        git add output/newsforllms_*.html
        git add output/newsforllms_*.md
        git add data/processed/wikipedia_*_events.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update news for LLMs - $(date +'%Y-%m-%d')" && git push)